apiVersion: v1
kind: ConfigMap
metadata:
  name: ebanking-config
  namespace: ebanking
data:
  application.properties: |
    spring.application.name=ebanking-transactions-api
    server.port=8080

    # Database Configuration
    spring.datasource.url=jdbc:postgresql://postgres-service:5432/ebanking
    spring.datasource.driver-class-name=org.postgresql.Driver
    spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
    spring.jpa.hibernate.ddl-auto=validate
    spring.jpa.show-sql=false

    # Kafka Configuration
    app.kafka.bootstrap-servers=kafka-service:9092
    app.kafka.consumer-group=ebanking-transactions-consumer
    app.kafka.transaction-topic=transaction-events

    # OpenAPI Configuration
    app.openapi.dev-url=http://localhost:8080
    app.openapi.prod-url=https://api.ebanking.nadeemr.com

    # Actuator Configuration
    management.endpoints.web.exposure.include=health,metrics,info,prometheus
    management.endpoint.health.show-details=always
    management.metrics.export.prometheus.enabled=true

    # Logging Configuration
    logging.level.com.nadeemr.ebanking=INFO
    logging.level.org.springframework.kafka=WARN
    logging.level.org.springframework.security=WARN
    logging.level.root=WARN

    # Cache Configuration
    spring.cache.type=simple
    spring.cache.cache-names=exchangeRates
