apiVersion: v1
kind: Secret
metadata:
  name: ebanking-secrets
  namespace: ebanking
type: Opaque
data:
  db-username: ZWJhbmtpbmdfdXNlcg== # ebanking_user (base64 encoded)
  db-password: ZWJhbmtpbmdfcGFzc3dvcmQ= # ebanking_password (base64 encoded)
  jwt-secret: bXlTZWNyZXRLZXkxMjM0NTY3ODkwMTIzNDU2Nzg5MDEyMzQ1Njc4OTAxMjM0NTY3ODkwMTIzNDU2Nzg5MA== # base64 encoded JWT secret
